# Health Check Endpoint
[[routes]]
path = "/api/v1/health"
method = "GET"
status_code = 200
response_body = '{"status": "healthy"}'
content_type = "application/json"
delay_ms = 200

# Multi Respones with GET Method
[[routes]]
path = "/api/v1/resource"
method = "GET"
status_code = 200
responses = [
  { 
    query = { "type" = "active" },
    status_code = 200,
    response_body = """
    {
      "message": "Resource retrieved successfully",
      "data": {
        "id": 1,
        "name": "Resource 1",
        "type": "active"
      }
    }
    """,
    content_type = "application/json"
  },
  { 
    query = { "type" = "inactive" },
    status_code = 200,
    response_body = """
    {
      "message": "Resource retrieved successfully",
      "data": {
        "id": 2,
        "name": "Resource 2",
        "type": "inactive"
      }
    }
    """,
    content_type = "application/json"
  }
]

# POST Method
[[routes]]
path = "/api/v1/resource"
method = "POST"
status_code = 201
response_body = '{"message": "Resource created successfully"}'
content_type = "application/json"
